# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-16 05:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('carrito', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetallesVenta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facturas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carrito.Factura')),
                ('productos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carrito.Producto')),
            ],
        ),
    ]
