# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-16 05:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('carrito', '0004_auto_20160516_0550'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detallesventa',
            name='facturas',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carrito.Factura'),
        ),
    ]
